<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\images\Brownie-Tarifi.webp" />
    <Content Remove="wwwroot\images\brownie.webp" />
    <Content Remove="wwwroot\images\coca.img" />
    <Content Remove="wwwroot\images\cocacola.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinhaSolucao.Biblioteca\MinhaCantina.Biblioteca.csproj" />
  </ItemGroup>

</Project>
